import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { NativeScriptModule } from 'nativescript-angular/nativescript.module';

import { AppRoutingModule } from './app-routing.module.tns';
import { AppComponent } from './app.component';
import { AutoGeneratedComponent } from './auto-generated/auto-generated.component';
import { PaymentsComponent } from './payments/payments.component';
import { PaymentMethodComponent } from './payment-method/payment-method.component';
import { ConnectComponent } from './connect/connect.component';
import { HistoryComponent } from './history/history.component';
import { HomeComponent } from './home/home.component';
import { LoginComponent } from './login/login.component';
import { LoginrouteComponent } from './loginroute/loginroute.component';
import { NavigationComponent } from './navigation/navigation.component';
import { PostingComponent } from './posting/posting.component';
import { SettingsComponent } from './settings/settings.component';
import { UpdateComponent } from './update/update.component';
import { DialogComponent } from './dialog/dialog.component';
import { SearchComponent } from './search/search.component';

import { LoginDirective } from './login.directive';
import { HomeDirective } from './home.directive';

import { PostingService } from './posting.service';
import { UserService } from './user.service';
import { TransferService } from './datatransfer.service';
import { DynamicAddService } from './dynamic-add.service';
import { PaymentService } from './payment.service';
import { PlacesAutocompleteService } from './places-autocomplete.service';

import { ModalDialogService } from "nativescript-angular/modal-dialog";

import { ReactiveFormsModule, FormsModule } from '@angular/forms';
import {MatInputModule} from '@angular/material/input';
import { AgmCoreModule } from '@agm/core';
import { ChatModule } from './chat/chat.module';
import { NgxPayPalModule } from 'ngx-paypal';
import { NgxBraintreeModule } from 'ngx-braintree';
import { HttpClientModule } from '@angular/common/http';


// Uncomment and add to NgModule imports if you need to use two-way binding
import { NativeScriptFormsModule } from 'nativescript-angular/forms';

// Uncomment and add to NgModule imports  if you need to use the HTTP wrapper
import { NativeScriptHttpClientModule } from 'nativescript-angular/http-client';
import { FloatBtnComponent } from './float-btn/float-btn.component';
import { AddModalComponent } from './add-modal/add-modal.component';
import { LocationComponent } from './location/location.component';
import { AddPaymentComponent } from './add-payment/add-payment.component';
import { AddCardPaymentComponent } from './add-card-payment/add-card-payment.component';
import { PaymentInfoComponent } from './payment-info/payment-info.component';
import { ConfirmationComponent } from './confirmation/confirmation.component';
import { MessageModalComponent } from './message-modal/message-modal.component';
import { WelcomeComponent } from './welcome/welcome.component';
import * as application from 'tns-core-modules/application';
import { NativeScriptFacebookModule } from "nativescript-facebook/angular";
import * as nsFacebook from 'nativescript-facebook';

// require('nativescript-nodeify')
// import { AmplifyAngularModule, AmplifyService } from 'aws-amplify-angular';

// import { AngularFireModule } from '@angular/fire';
// import { AngularFirestoreModule } from '@angular/fire/firestore';
// import { AngularFireStorageModule } from '@angular/fire/storage';
// import { AngularFireAuthModule } from '@angular/fire/auth';
// import { environment } from '../environments/environment';

application.on(application.launchEvent, function (args) {
    nsFacebook.init("2272129649677747");
});

@NgModule({
  declarations: [
    AppComponent,
    LoginDirective,
    LoginComponent,
    HomeComponent,
    HomeDirective,
    HistoryComponent,
    SettingsComponent,
    PostingComponent,
    UpdateComponent,
    ConnectComponent,
    LoginrouteComponent,
    DialogComponent,
    NavigationComponent,
    AutoGeneratedComponent,
    PaymentsComponent,
    PaymentMethodComponent,
    SearchComponent,
    FloatBtnComponent,
    AddModalComponent,
    LocationComponent,
    AddPaymentComponent,
    AddCardPaymentComponent,
    PaymentInfoComponent,
    ConfirmationComponent,
    MessageModalComponent,
    WelcomeComponent
  ],
  imports: [
    NativeScriptModule,
    AppRoutingModule,
    NativeScriptHttpClientModule,
    ReactiveFormsModule,
    NativeScriptFormsModule,
    MatInputModule,
    AgmCoreModule.forRoot({
      apiKey: 'AIzaSyAITxS1jmf8PMtazRguWcAfWQxW1kPOoYg'
    }),
    ChatModule,
    NgxPayPalModule,
    // NgxBraintreeModule,
    HttpClientModule,
    NativeScriptFacebookModule,
    // AngularFireModule.initializeApp(environment.firebase),
    // AngularFirestoreModule, // imports firebase/firestore, only needed for database features
    // AngularFireAuthModule, // imports firebase/auth, only needed for auth features,
    // AngularFireStorageModule // imports firebase/storage only needed for storage features
  ],
  providers: [PostingService, TransferService, DynamicAddService, UserService, PaymentService, ModalDialogService, PlacesAutocompleteService],
  bootstrap: [AppComponent],
  entryComponents: [PostingComponent, PaymentMethodComponent, AddModalComponent, LocationComponent, AddPaymentComponent, AddCardPaymentComponent, 
  PaymentInfoComponent, ConfirmationComponent],
  schemas: [NO_ERRORS_SCHEMA]
})
/*
Pass your application module to the bootstrapModule function located in main.ts to start your app
*/
export class AppModule { }
