// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_1m6yRE1j7",
    "aws_user_pools_web_client_id": "sfgfnmo1phgclaq7hjgp90cke",
    "oauth": {}
};


export default awsmobile;
